server:
  port: 8050
  tomcat:
    max-http-header-size: 8192
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kh?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 1996815a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.khht.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.khht.mapper: debug